apiVersion: v1
kind: Pod
metadata:
  name: newapp
spec:
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
