apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    purpose: demo
    name: demo-update
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: demo-update
  template:
    metadata:
      labels:
        purpose: demo
        name: demo-update
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SPECIAL_ENV_VALUE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.config.name }}
                key: color
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
