# Default values for myfirstcahrt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: staginghelmdeployment
  replicaCount: 3
  image:
    app: nginx
    version: latest

service:
  name: staginghelmservice
  type: NodePort
  port: 80
  targetPort: 80
  NodePort: 31234

proxy:
  neabled: true
