apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: apache
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      {{- include "nodeport" . | indent 6 -}}
      {{- else if eq .Values.service.type "LoadBalancer" }}
      {{- include "loadbalancer" . | indent 6 }}
      {{- else }}
      port: 90
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: apache