apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        # readinessProbe:
        #   httpGet:
        #     scheme: HTTPS
        #     path: /healthz
        #     port: 8443
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/healthz
            port: 80
        resources: {}
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
        - containerPort: 80
